project:
  type: website
  output-dir: docs

website:
  title: "<img src='./Images/logo.png' alt='Project Logo' style='height:80px;'>"
  navbar:
    background: primary
    left:
      - text: "Home"
        href: index.html
      - text: "Research Questions"
        href: research-questions.html
      - text: "Data Sources"
        href: data-sources.html
      - text: "Timeline"
        href: timeline.html
      - text: "Technical feasibility"
        href: technical-feasibility.html

format:
  html:
    theme: cosmo
    css: styles.css
    include-in-header: header.html
