---
title: "Technical feasability"
format: html
---

+------------------------------------------+--------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------+
|                                          | Potential Issue                                                                                                          | Back up plan                                                                                |
+==========================================+==========================================================================================================================+=============================================================================================+
| **Technical Issues**                     | -   API Rate Limits                                                                                                      | -   Use alternate APIs if one fails: e.g World Bank API, other museum APIs, Twitter api     |
|                                          | -   Changes in API                                                                                                       |                                                                                             |
|                                          | -   Large datasets from Smithsonian or Reddit may slow processing and overwhelm storage                                  | -   Keep an eye on the number of requests being made                                        |
|                                          |                                                                                                                          |                                                                                             |
|                                          |                                                                                                                          | -   Use API-provided bulk download options, like Smithsonian's collections dump.            |
|                                          |                                                                                                                          |                                                                                             |
|                                          |                                                                                                                          | -   Download and store datasets locally for continued analysis if APIs become inaccessible. |
+------------------------------------------+--------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------+
| **Data Quality Issues Incomplete Data:** | -   FRED may lack micro-economic context                                                                                 | -   Clean the data to remove any irrelevant content                                         |
|                                          | -   Reddit content can include spam, irrelevant posts, or off-topic discussions                                          |                                                                                             |
|                                          | -   Data might reflect institutional or user biases                                                                      |                                                                                             |
+------------------------------------------+--------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------+
| **Analysis**                             | -   Assigning art themes to economic or social periods is inherently interpretive and may lead to subjective conclusions | -   Clearly state assumptions, limitations, and potential biases in the project's findings. |
|                                          | -   Correlations does not mean causation                                                                                 |                                                                                             |
+------------------------------------------+--------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------+
| **Data Privacy: Scraping**               | -   Data must comply with ethical guidelines and the API's terms of service                                              | -   Review and strictly adhere to API terms of service and usage policies                   |
+------------------------------------------+--------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------+