project:
  type: website
  output-dir: ../docs

website:
  title: "<img src='./images/logo.png' alt='Project Logo' style='height:80px;'>"
  navbar:
    background: primary
    left:
      - text: "Home"
        href: index.html
      - text: "Data Collection & Processing"
        href: data.html
      - text: "Our Findings"
        menu:
          - text: "Data Visualisations"
            href: visualisations.html
          - text: "Conclusions"
            href: conclusions.html
      - text: "Contributions"
        href: contributions.html
    search: true
    tools:
      - icon: github
        menu:
          - text: Source Code
            href:  https://github.com/lse-ds105/ds105a-2024-project-data_dazzlers.git
    back-to-top-navigation: true

format:
  html:
    css: styles.csser
    toc: true
    include-in-header: header.html
